engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
- frontend/vendor/**/*
- frontend/bower_components/**/*
- frontend/node_modules/**/*
- public/assets/**/*
